### ISSUE TITLE
Download_MetaPathPredictE_Models Command Not working

### ISSUE THREAD

**Issue by Shane-Kieffer** [d-mcgrath/MetaPathPredict-E#1]
Hello! I am running into an issue with Step 5 of the installation process. Upon trying to run the Download_MetaPathPredictE_Models command, I received the following message:

Traceback (most recent call last):
  File "C:\Users\kief065\AppData\Local\anaconda3\envs\MetaPathPredict-E\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kief065\AppData\Local\anaconda3\envs\MetaPathPredict-E\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\kief065\AppData\Local\anaconda3\envs\MetaPathPredict-E\Scripts\Download_MetaPathPredictE_Models.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'metapathpredict_e.download_models'

Looking into it, I found that the Download_MetaPathPredictE_Models,py file was not cloned from the repository and was not listed in the src directory in my powershell. 
Any help resolving this issue would be greatly appreciated, thanks for your time!

**Comment by d-mcgrath** [comment]
Hi Shane, I forgot to close this after our email exchange. This installation issue has been fixed. Closing this now!
